services:
  t3-custom-template-postgresql:
    image: postgres
    container_name: t3-custom-template-postgresql
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  data:
